### ISSUE TITLE
Add a logger

### ISSUE THREAD

**Issue by Michael55555** [Michael55555/discord-bot-creator#10]
To debug errors better in production, we need a logger. It should just put new logs in a local log file.

## Tasks
- [ ] Create Logger
- [ ] Replace important logs with logger function calls

**Comment by Michael55555** [comment]
You're welcome! Let me know if I can be helpful somehow

**Comment by Michael55555** [comment]
I'll take this from here, hope it's okay 🙂

**Comment by m5x5** [comment]
Fixed with #25
