### ISSUE TITLE
(JS-0128) Should not have unused variables

### ISSUE THREAD

**Issue by m5x5** [Michael55555/discord-bot-creator#9]
## Description
Found variables that are declared but not used anywhere.
Please be careful with removal, there might be an eval statement using those variables.

## Occurrences
There are 109 occurrences of this issue in the repository.

See all occurrences on DeepSource &rarr; [deepsource.io/gh/Michael55555/discord-bot-creator/issue/JS-0128/occurrences/](https://deepsource.io/gh/Michael55555/discord-bot-creator/issue/JS-0128/occurrences/)

**Comment by Michael55555** [comment]
I forgot that DeepSource still has many unused variables. Would you like to remove them too @rajoriaakash?

**Comment by rajoriaakash** [comment]
Yeah sure 
I just hope I don't end up bugging the app more :) but I would like to try
